### ISSUE TITLE
Run kubelinter on the manifests

### ISSUE THREAD

**Issue by gbenhaim** [konflux-ci/konflux-ci#100]
We should verify our manifests using kubelinter. It can be done using a Github action.
Reference https://github.com/redhat-appstudio/infra-deployments/blob/main/.github/workflows/kube-linter.yaml

**Comment by yftacherzog** [comment]
The workflow is in place. Some [exceptions](https://github.com/konflux-ci/konflux-ci/blob/main/.github/.kube-linter-config.yaml) are still present and should be addressed.
