### ISSUE TITLE
README - smee manifests does not have a Homepage URL placeholder 

### ISSUE THREAD

**Issue by avi-biton** [konflux-ci/konflux-ci#124]
In the README we refer to a `Homepage URL` placeholder in the smee manifest.
This field does not exist in the manifest (it has a value)

We can either remove the comment from the [README](https://github.com/konflux-ci/konflux-ci/blob/main/README.md?plain=1#L168) or add this placeholder to the [manifest](https://github.com/konflux-ci/konflux-ci/blob/main/smee/smee-client.yaml#L29)

**Comment by yftacherzog** [comment]
That `Homepage URL` is referring to the creation of the github app rather than the smee client manifest.
