### ISSUE TITLE
README - Remove the title Using Konflux

### ISSUE THREAD

**Issue by avi-biton** [konflux-ci/konflux-ci#125]
Remove the title [Using Konflux](https://github.com/konflux-ci/konflux-ci/blob/main/README.md?plain=1#L687)
and indent the titles under it (the main title should be `Namespace and User Management`)

**Comment by yftacherzog** [comment]
I'll do it as part of https://github.com/konflux-ci/konflux-ci/pull/123

**Comment by avi-biton** [comment]
Thanks
