### ISSUE TITLE
serviceaccount "default" not found

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#161]
When running deploy-deps.sh just after creating the cluster, the script tends to fail. This is not an issue anymore after waiting a few seconds. Need to find a way to avoid the error message (e.g. separate creating of the ns and the pvc and wait between them or something like that).

```bash
→ ./deploy-deps.sh
Checking requirements
kubectl is installed
openssl is installed

All requirements are met
Continue
Testing PVC creation for default storage class
Creating PVC from './dependencies/pre-deployment-pvc-binding' using the cluster's default storage class
namespace/test-pvc-ns unchanged
persistentvolumeclaim/test-pvc unchanged
Error from server (Forbidden): error when creating "./dependencies/pre-deployment-pvc-binding": pods "test-pvc-consumer" is forbidden: error looking up service account test-pvc-ns/default: serviceaccount "default" not found
```

**Comment by yftacherzog** [comment]
The fix seem to cause a similar race condition. Reopening.

**Comment by rh-hemartin** [comment]
Hey, I'm hitting the same problem. I think the only way to deal with this is to separate the Pod creation from the namespace creation and wait for the service account to be created.
