### ISSUE TITLE
Automate the Smee setup flow

### ISSUE THREAD

**Issue by ifireball** [konflux-ci/konflux-ci#169]
Manually setting up the smee.io channel and the client is cumbersome, especially when [tkn pac bootstrap][1] already automated it .

[1]: https://pipelinesascode.com/docs/guide/cli/

Suggestions:

1. Automate the process like `tkn pac` does (Perhaps simply call it directly)
2. Save the channel information to a file somehow so it can be reused if the cluster is recreated

**Comment by yftacherzog** [comment]
I'm not sure I want to install PaC's code as it will mean another dependency for the user, which I think is more complicated than creating the channel.

Looking at their code, it seems as it creates the channel by generating a random string with 12 chars or more and appending it to this URL: https://hook.pipelinesascode.com/.
You don't need to actually create the channel afterwards.

With https://smee.io/, you don't have to create the channel either and it doesn't seem as there's any limitation to the string appended to this URL (it could be a single character).

All in all, we can automate this. Just need to figure out what's the best way to save the value once generated. Maybe can store a kustomize patch file with the channel name (add it to gitignore). `deploy-deps.sh` can generate the value and store it to the patch if it doesn't exist and deploy the smee manifest as part of `deploy-deps.sh`.
