### ISSUE TITLE
UI - Favorites doesn't work 

### ISSUE THREAD

**Issue by shairevivo** [konflux-ci/konflux-ci#173]
When you try to use the favorites functionality nothing is actually saved and it doesn't work (nor needed IMHO)
![2024-06-18_12-21](https://github.com/konflux-ci/konflux-ci/assets/98468006/8e522fe8-a98d-4227-9958-bb40a86b4d1b)

**Comment by yftacherzog** [comment]
Not sure that this is directly related to this repo. We might need to understand under which repo this issues needs to be opened.

**Comment by shairevivo** [comment]
Well, it is part of the install ... I'll wait for your input as I have many more UI issues to submit.

**Comment by yftacherzog** [comment]
Don't hold back. Create them here and we'll figure out later if they need to be reopened elsewhere.

**Comment by gbenhaim** [comment]
solved by https://github.com/konflux-ci/konflux-ci/pull/815
