### ISSUE TITLE
UI - Preview button doesn't work and yield in 404  

### ISSUE THREAD

**Issue by shairevivo** [konflux-ci/konflux-ci#174]
Trying to enable preview button end with a 404 message. 
Not sure what this preview even mean in this context nor it's needed
![2024-06-18_12-22](https://github.com/konflux-ci/konflux-ci/assets/98468006/16abb7aa-169d-446c-80d2-6de1b0d2da28)

**Comment by gbenhaim** [comment]
solved by https://github.com/konflux-ci/konflux-ci/pull/815
