### ISSUE TITLE
UI - settings in non functional and contain unnecessary step

### ISSUE THREAD

**Issue by shairevivo** [konflux-ci/konflux-ci#176]
When clicking on settings i get a drop down list (problem #1) instead of going to settings directly + when clicking it i get 404 message which then the url get messed up trying to go back.
![2024-06-18_12-25](https://github.com/konflux-ci/konflux-ci/assets/98468006/ad2b4483-35b9-486c-8574-fc54e84c72fe)

**Comment by gbenhaim** [comment]
solved by https://github.com/konflux-ci/konflux-ci/pull/815
