### ISSUE TITLE
UI - Services drop down seems to be wrong 

### ISSUE THREAD

**Issue by shairevivo** [konflux-ci/konflux-ci#177]
Clicking on the services drop down seems to contain wrong information. not sure which services were intended to appear there. 
![2024-06-18_14-40](https://github.com/konflux-ci/konflux-ci/assets/98468006/e540753b-df83-4b65-a3ec-a66b18066322)

**Comment by gbenhaim** [comment]
solved by https://github.com/konflux-ci/konflux-ci/pull/815
