### ISSUE TITLE
UI - Konflux title below the logo seems to be redundant

### ISSUE THREAD

**Issue by shairevivo** [konflux-ci/konflux-ci#179]
Considering the Konflux logo above it it looks a bit redundant 
![2024-06-18_14-54](https://github.com/konflux-ci/konflux-ci/assets/98468006/7d6cdaab-641b-4092-b94c-1404574371b5)

**Comment by gbenhaim** [comment]
solved by https://github.com/konflux-ci/konflux-ci/pull/815
