### ISSUE TITLE
deploy-konflux.sh fails with Failed to initialise OAuth2 Proxy: error initialising provider ... Realm does not exist

### ISSUE THREAD

**Issue by pbabinca** [konflux-ci/konflux-ci#192]
Deployment of Konflux with `./deploy-konflux.sh` fails with following two lines:

```
[2024/07/02 14:04:12] [main.go:58] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: unexpected status "404": {"error":"Realm does not exist","error_description":"For more on this error consult the server log at the debug level."}
```

---

I have created a VM with 12 GiB RAM, 16 GiB storage, 4 VCPUs.

I:
1. managed to create the cluster,
2. updated `fs.inotify` to avoid too many opened files,
3. updated pid limit,
4. installed dependencies

Full log of `./deploy-konflux.sh` is attached as: [deploy-konflux.log](https://github.com/user-attachments/files/16069821/deploy-konflux.log).

Repeated run of the command failed with the same error.

**Comment by yftacherzog** [comment]
Thanks for raising this. We'll look into that.

**Comment by gbenhaim** [comment]
@pbabinca can you please run `generate-err-logs.sh` and upload the output?
for some reason the Keycloak realm wasn't created, the logs will help to understand the root cause.

**Comment by yftacherzog** [comment]
When you mention that you created a VM with 4 CPUs, do you mean that the cluster had 4 CPUs available or the entire VM on which the cluster runs have 4 CPUs?

The cluster itself needs 4 CPUs available . Having less than that might cause things to come up slower or not come up at all, which might make the setup fail.

**Comment by pbabinca** [comment]
> When you mention that you created a VM with 4 CPUs, do you mean that the cluster had 4 CPUs available or the entire VM on which the cluster runs have 4 CPUs?

@yftacherzog, I'm not sure what is the difference between these options. The VM has been created with [...] `virsh --cpu host --vcpu 4` [...] so I believe the VM had fully available 4 CPUs. The hypvervisor itself is much more powerful.

> @pbabinca can you please run generate-err-logs.sh and upload the output?

@gbenhaim, Unfortunately since this report I had to reinstall the whole machine including all VMs. Since then I'm not getting the same error because this time I got error even earlier: #205.

**Comment by yftacherzog** [comment]
> @yftacherzog, I'm not sure what is the difference between these options. The VM has been created with [...] `virsh --cpu host --vcpu 4` [...] so I believe the VM had fully available 4 CPUs. The hypvervisor itself is much more powerful.

Checking the amount of resources that the kind cluster requires when Konflux is up, we saw that 8 gigs of RAM and 4 CPUs should be enough for all the pods on the cluster with some wiggle room.
In other words, the OS needs to leave those resources free for the cluster, so it should have more than 8 gigs of RAM and 4 CPUs, as other processes on the OS consume resources as well.

We specifically tested with a 4 CPUs VM, and indeed things were sometimes failing to start and sometimes taking too long to start.

All in all, as mentioned in https://github.com/konflux-ci/konflux-ci/issues/205, I think you're seeing resources-related issues. It's possible that there are other issues as well, but I suspect the cluster is not stable enough to troubleshoot them effectively.
