### ISSUE TITLE
using tag/branch as a revision in pipelineref could be problematic

### ISSUE THREAD

**Issue by psturc** [konflux-ci/konflux-ci#193]
So I saw this error in the release-pipeline when trying to release the app according to the [guide](https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#trigger-the-release):
```
STEP-UPDATE-CR-STATUS
...
+ kubectl --warnings-as-errors=true patch release -n user-ns2 test-9zlqc-rtmjw --type=merge --subresource status --patch 'status: {'\''artifacts'\'':{"images":[{"arches":["amd64"],"name":"testrepo","shasum":"sha256:1774d3a98948639412127c96b50fe828a98b8b54797d058b3789a48e42799da8","urls":["quay.io/psturc_org/test-images:latest","quay.io/psturc_org/test-images:latest-1720024572","quay.io/psturc_org/test-images:4da87e0","quay.io/psturc_org/test-images:4da87e06679bd33388963f0f8d9b4d737f9b576b","quay.io/psturc_org/test-images:1774d3a98948639412127c96b50fe828a98b8b54797d058b3789a48e42799da8"]}]}}'
Error from server (Forbidden): releases.appstudio.redhat.com "test-9zlqc-rtmjw" is forbidden: User "system:serviceaccount:managed-ns2:appstudio-pipeline" cannot get resource "releases/status" in API group "appstudio.redhat.com" in the namespace "user-ns2"
```

After a bit of digging I found out that [the failing script from related taskrun](https://github.com/konflux-ci/release-service-catalog/blame/647155d2bea584e72190ee76ce7490ecf4e2066f/tasks/update-cr-status/update-cr-status.yaml#L56) relies on [this clusterrole rule](https://github.com/redhat-appstudio/infra-deployments/blame/986f4f543e58d3c8c3b117c04024fc2588fd7176/components/release/base/release-pipeline-resources-clusterrole.yaml#L34) which is missing from the [release-pipeline-resource-role rbac defined in this repo](https://github.com/konflux-ci/konflux-ci/blob/eaf689a92d2b977edd4a5b6310035dc772b7709f/konflux-ci/release/core/rbac.authorization.k8s.io_v1_clusterrole_release-pipeline-resource-role.yaml#L26).

And even after updating the clusterrole on my kind cluster I hit another error:
```
+ kubectl --warnings-as-errors=true patch release -n user-ns2 test-2h75t-dzbr2 --type=merge --subresource status --patch 'status: {'\''artifacts'\'':{"images":[{"arches":["amd64"],"name":"testrepo","shasum":"sha256:120906b40dfa78a65ebb4577ba5c03dfe42e62078497f0e75304aeef102fda7c","urls":["quay.io/psturc_org/test-images:latest","quay.io/psturc_org/test-images:latest-1720027800","quay.io/psturc_org/test-images:f5a7608","quay.io/psturc_org/test-images:f5a760819cb21975e43e3c96e19961549a638ef0","quay.io/psturc_org/test-images:120906b40dfa78a65ebb4577ba5c03dfe42e62078497f0e75304aeef102fda7c"]}]}}'
Warning: unknown field "status.artifacts"
```
Which was caused by [quite a recent change in Release CRD](https://github.com/konflux-ci/release-service/blame/73612c0b60658392c6786b563a810fa122585fa6/api/v1alpha1/release_types.go#L59)

And all of that was caused by a fact that the release pipeline reference pointed to [production branch](https://github.com/konflux-ci/konflux-ci/blob/eaf689a92d2b977edd4a5b6310035dc772b7709f/test/resources/demo-users/user/managed-ns2/rpa.yaml#L27-L28) that gets updated over time.

So that led me to a thought whether we could use **fixed revision values (i.e. commit IDs)** in the PipelineRefs **instead of tags/branches** which could get updated and cause errors like these. 
That would practically mean to update [these test resources](https://github.com/search?q=repo%3Akonflux-ci%2Fkonflux-ci%20%22-%20name%3A%20revision%22&type=code).

Wdyt?

**Comment by yftacherzog** [comment]
Thanks for raising this and providing all the details.
The approach you mention makes sense to me.
