### ISSUE TITLE
Documentation - Add webhook secret error message to troubleshoot

### ISSUE THREAD

**Issue by avi-biton** [konflux-ci/konflux-ci#212]
When creating a github application without a webhook secret we get this error in our opened PR:
`There was an issue validating the commit: "could not validate payload, check your webhook secret?: no signature has been detected, for security reason we are not allowing webhooks that has no secret"`

We should add it to the troubleshooting section of the documentation

**Comment by yftacherzog** [comment]
You mean the secret was not added when creating the app?

**Comment by avi-biton** [comment]
> You mean the secret was not added when creating the app?

Yes
