### ISSUE TITLE
Remove the nginx-ingress controller

### ISSUE THREAD

**Issue by gbenhaim** [konflux-ci/konflux-ci#51]
It's not being used, there is no point to deploy it.

**Comment by cmoulliard** [comment]
Why did you removed the ingress controller as we need it to configure routes to access the cluster remotely ? 
@gbenhaim

**Comment by gbenhaim** [comment]
@cmoulliard in the context of the Kind deployment since the Konflux proxy is used for exposing the different Konflux endpoints https://github.com/konflux-ci/konflux-ci/tree/main/konflux-ci/ui/core/proxy

The proxy is exposed via Node Port Service.

When deploying Konflux on outside of Kind, for example EKS, I would leave it for the cluster administrator to configure they preferred ingress if he/she find they need it. I don't think it should be Konflux responsability.

**Comment by cmoulliard** [comment]
> The proxy is exposed via Node Port Service.

We can for sure access the cluster using the IP of the machine running the cluster + port node but then keycloak still redirects the traffic to the localhost which is also an issue that we will have with smee, etc

I can access the cluster using the following url `https://10.0.77.131/=9443` but then I'm redirected for the keycloak auth to: `https://localhost:9443/idp/realms/redhat-external/protocol/openid-connect/auth?clien[%E2%80%A6]state=97cef8a8144643488bd6507cfb05c26a&response_mode=fragment`
