### ISSUE TITLE
Fedora: make users' username be their FAS id, not their email, in the fedora cluster

### ISSUE THREAD

**Issue by ralphbean** [konflux-ci/konflux-ci#557]
I'm hearing from users that in the [fedora instance of konflux](https://gist.github.com/ralphbean/a3644111a549e8cedb0b207f90d42dc9) run by the [fedora + konflux sig](https://github.com/konflux-ci/community/blob/main/sigs/fedora.md) that they would like their usernames to be their FAS usernames, not their email address associated with their FAS usernames. It's just more natural for them.

**Comment by ralphbean** [comment]
(This issue may not be filed in the right place. If it belongs somewhere else, help me route it!)

**Comment by yftacherzog** [comment]
cc @gbenhaim

**Comment by ralphbean** [comment]
Moved to https://gitlab.com/fedora/infrastructure/konflux/infra-deployments/-/issues/5
