### ISSUE TITLE
Cannot create a component - Not found

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/konflux-ci#566]
## Issue

I installed the latest commit of konflux 4c6d0493b8e318d3406ca746c0b9236a7627291f on a VM using kind `0.24`. No issues have been reported during the installation of konflux except `docker rate limit` that I fixed.

When I access the UI for the user `user-ns1` then I got such an error when creating a Component

**Note**: UI message `Not found` don't really help the users !

![Screenshot 2024-10-21 at 12 46 29](https://github.com/user-attachments/assets/65ebb105-bef4-4210-a7b4-85f8be588bad)

Using chrome debugger I see such a HTTP 404 error 
![Screenshot 2024-10-21 at 12 58 30](https://github.com/user-attachments/assets/2aa124c4-1a4a-47ee-bc21-ca3a1af9e1d8)

## Additional information

Git repo: https://github.com/ch007m/my-konflux-quarkus-1.git
Dockerfile path: src/main/docker/Dockerfile.jvm

Application CR is well created
```
k get Application/snowdrop -n user-ns1 -oyaml
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  annotations:
    application.thumbnail: "8"
  creationTimestamp: "2024-10-21T10:45:45Z"
  generation: 1
  name: snowdrop
  namespace: user-ns1
  resourceVersion: "21283"
  uid: d10d9d30-50b6-4e96-b033-1b98256c380c
spec:
  displayName: snowdrop
```

**Comment by cmoulliard** [comment]
I suspect that a resource has not been installed (= imagerepositories) which is defined part of the [RBAC](https://github.com/konflux-ci/konflux-ci/blob/ed1703a39d1397b67f3a14909b7a2ca9db00490e/konflux-ci/rbac/core/rbac.yaml#L22) file.

**Comment by yftacherzog** [comment]
Did you install image-controller per the readme? Look for this line:

To do that, [Follow the procedure](https://github.com/konflux-ci/konflux-ci/blob/main/docs/quay.md#automatically-provision-quay-repositories-for-container-images) to configure a Quay.io application and deploy image-controller

**Comment by cmoulliard** [comment]
> Did you install image-controller per the readme? Look for this line:

I don't think so. Is it possible to show a more usere friendly message within the console to tell to the users what the issue is ?

**Comment by yftacherzog** [comment]
> > Did you install image-controller per the readme? Look for this line:
> 
> I don't think so. Is it possible to show a more usere friendly message within the console to tell to the users what the issue is ?

I agree this is not self-explanatory. 

As far as I'm aware this dependency in image-controller is going to be changed, and there are also changes being worked on for the UI as a whole, so I expect this is not to be an issue in the long term. In the meantime, we have this error documented in this repo to guide users that encounter it (see the first note under [Create Application and Component via the Konflux UI](https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#create-application-and-component-via-the-konflux-ui)).

**Comment by gbenhaim** [comment]
+1 @yftacherzog 
I created a ticket for removing the dependency on image controller https://github.com/konflux-ci/konflux-ci/issues/830
