### ISSUE TITLE
Upgrade to the latest version of Tekton

### ISSUE THREAD

**Issue by arewm** [konflux-ci/konflux-ci#567]
I wanted to change the multi-arch build pipeline to use a matrix of size one by default in https://github.com/konflux-ci/build-definitions/pull/1518. The bug preventing us from being able to do that was resolved in https://github.com/tektoncd/pipeline/pull/8158. In order to consume this change, we need to upgrade to at least [v0.73.0 for the operator](https://github.com/tektoncd/operator/blob/v0.73.0/go.sum#L1764-L1765) as the change was included in `tektoncd/pipelines` [v0.62.1](https://github.com/tektoncd/pipeline/releases/tag/v0.62.1).

**Comment by yftacherzog** [comment]
@arewm have a look at https://github.com/konflux-ci/konflux-ci/pull/604 and let me know if this is what you had in mind.

**Comment by yftacherzog** [comment]
This issue is currently blocked by https://github.com/konflux-ci/konflux-ci/issues/518

**Comment by yftacherzog** [comment]
The blocking issue was addressed yesterday and this upgrade is now done.
