### ISSUE TITLE
Improve the section customization of the UI

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/konflux-ci#637]
## Improvement

The following [section](https://github.com/konflux-ci/konflux-ci/tree/main/konflux-ci/ui#customizations) of the README to install the konflux UI mentions that we must "Updating the hostname that will be used for the routes." before to deploy it. 

Question: What is the hostname that we are talking about here ? where such hostname should be updated ? Is it the hostname used by an Openshift route or Ingress ?

**Comment by avi-biton** [comment]
@cmoulliard If you don't mind, I would like to close this issue.
The README file was changed with the new UI scaffolding and this issue is no longer relevant.

**Comment by cmoulliard** [comment]
Can you point within the documentation where you did the change as I don't see anything about how to customize the UI (pop up list, etc) ? @avi-biton

**Comment by yftacherzog** [comment]
The original issue mentions parts that since there were removed from that readme.
What is it that you're currently seeing as missing from the documentation in this regard?
We can then try to introduce it.

**Comment by cmoulliard** [comment]
Sorry. This is my fault. Forget my remark. I will remove it !
