### ISSUE TITLE
Build service requires "trusted-ca" config map

### ISSUE THREAD

**Issue by gbenhaim** [konflux-ci/konflux-ci#688]
After upgrading to commit 0d08520e1e375904b755e1f481d29034f75d88f6 the deployment of the build-service doesn't start since it requires a configmap name `trusted-ca`. I'm deploying konflux-ci on an Openshift cluster using ArgoCD. This is the path to the build-service manifests I use `https://github.com/konflux-ci/konflux-ci/konflux-ci/build-service/core`

**Comment by yftacherzog** [comment]
`trusted-ca` is the configmap that is generated by trust-manager that we're using for the internal registry. Did cert-manager and trust-manager deployed correctly? What's the status on the Bundle resource?
