### ISSUE TITLE
increase retry count or sleep time

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#75]
Some steps inside the deploy-deps scripts tend to fail randomly on retry. We might need to increase the retry count or increase the sleep time.

**Comment by avi-biton** [comment]
We encountered timeout when we used low resources VM for the deployment.
The only timeout we got was for the `keycloak`
I suggest we will increase the `keycloak` timeout for start.

**Comment by yftacherzog** [comment]
I see it also for this:
```bash
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
error: no matching resources found
error: no matching resources found
error: no matching resources found
```

I'm testing on a branch that doesn't have the retry message, but I think this is happening on the retry in `deploy_cert_manager()`.

**Comment by avi-biton** [comment]
@yftacherzog Which configuration did you use?
was it on your laptop?

**Comment by yftacherzog** [comment]
> @yftacherzog Which configuration did you use? was it on your laptop?

This is the branch I used: https://github.com/gbenhaim/konflux-ci/tree/import-flow
It was on my laptop. It's not the first time this happens for me. My guess is that it sometimes takes a few seconds for the cert-manager pod to appear so those retries fail.
