### ISSUE TITLE
UI - Missing link to Pipeline Run in the the Releases tab

### ISSUE THREAD

**Issue by avi-biton** [konflux-ci/konflux-ci#83]
Expected:
Once a release is been triggered, a Pipeline Run link should appear in the `Releases` tab

Actual:
The Pipeline Run link is empty

**Comment by yftacherzog** [comment]
Looking at the downstream production deployment, it seems to be the same.

**Comment by ralphbean** [comment]
Ah, it is likely rbac. If you don't have rights to view things in that release workspace, then the link is absent. If you do, then HAC should render it. (True in the downstream RH deployment.) Ping an admin of that workspace and they can give you view rights there.
